add checks for the erlang_js application (needed for the Map-Reduce framework)
The erlang_js library must be installed to erlang's lib directory in order to work.

diff --git a/bin/scalarisctl.in b/bin/scalarisctl.in
--- a/bin/scalarisctl.in
+++ b/bin/scalarisctl.in
@@ -358,6 +358,18 @@ checkinstallation() {
         echo -n "Continuing basic tests..."
     fi
 
+    CHECKCONFIGMSG=`$ERL -noinput -sasl sasl_error_logger false -boot start_sasl \
+        -eval "ok = application:start(erlang_js), {ok, JS} = js_driver:new(), ok = js:define(JS, <<\"var addOne = function(a){ return a + 1; }\">>), {ok,4} = js:call(JS, <<\"addOne\">>, [3]), halt(0)." 2>&1`
+    FAILED=$?
+    if [ $FAILED -ne 0 ]; then
+        echo -e "$MSG_FAILED"
+        echo "$CHECKCONFIGMSG"
+        echo "WARNING: unable to start the erlang_js application"
+        echo " You won't be able to use Scalaris' Map-Reduce framework."
+        echo "We were trying to run: $ERL -noinput -sasl sasl_error_logger false -boot start_sasl -eval \"ok = application:start(erlang_js), {ok, JS} = js_driver:new(), ok = js:define(JS, <<\"var addOne = function(a){ return a + 1; }\">>), {ok,4} = js:call(JS, <<\"addOne\">>, [3]), halt(0).\""
+        echo -n "Continuing basic tests..."
+    fi
+
     echo -e "$MSG_DONE"
 
     echo "Running Scalaris run-time tests..."
