- fixing configure for R13

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2645,7 +2645,14 @@ echo "$as_me: please consider running install.sh in the common_test directory ot
 fi
 
 
-cat >conftest.$ac_ext <<_ACEOF
+if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
 -module(conftest).
 -export([start/0]).
 -type(mytype()::gb_tree()).
@@ -2654,31 +2661,17 @@ ok
 .
 
 _ACEOF
-rm -f conftest.$ac_objext
-if { (ac_try="$ac_compile"
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
 case "(($ac_try" in
   *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
   *) ac_try_echo=$ac_try;;
 esac
 eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_compile") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_erl_werror_flag" || test ! -s conftest.err'
-  { (case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_try") 2>&5
+  (eval "$ac_link") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
   { (case "(($ac_try" in
   *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
   *) ac_try_echo=$ac_try;;
@@ -2691,14 +2684,18 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
   GBTREESISBUILTIN=", {d, types_are_builtin}"; { echo "$as_me:$LINENO: gb_tree() is a built-in type" >&5
 echo "$as_me: gb_tree() is a built-in type" >&6;}
 else
-  echo "$as_me: failed program was:" >&5
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	GBTREESISBUILTIN=""; { echo "$as_me:$LINENO: gb_tree() is not built-in" >&5
+( exit $ac_status )
+GBTREESISBUILTIN=""; { echo "$as_me:$LINENO: gb_tree() is not built-in" >&5
 echo "$as_me: gb_tree() is not built-in" >&6;}
 fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
 
-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
 
 
 
