Python-API: guard execution from empty PYTHON{2,3} variables
also use /bin/false if python was not found

diff --git a/python-api/scalaris.in b/python-api/scalaris.in
--- a/python-api/scalaris.in
+++ b/python-api/scalaris.in
@@ -22,6 +22,11 @@ SCALARISDIR=@libdir@/scalaris
 PYTHON2="@PYTHON2@"
 SCALARISCLIENT_PYTHON2="@PYTHON2SITELIBDIR@/scalaris_client.py"
 
+if [ -x "$PYTHON2" -o "x$PYTHON2" = "x/bin/false" ] ; then
+  echo "Python not found or not executable: $PYTHON2"
+  exit 1
+fi
+
 for arg in "$@"; do
   args="$args \"$arg\""
 done
