checkinstallation: properly wait for the started node before starting runtime tests (max 60s)

diff --git a/trunk/bin/scalarisctl.in b/trunk/bin/scalarisctl.in
--- a/trunk/bin/scalarisctl.in
+++ b/trunk/bin/scalarisctl.in
@@ -383,7 +383,30 @@ checkinstallation() {
         $0 -c "$SCALARIS_COOKIE" -e "$erl_flags" -d -f -s -m -n "$NODE_NAME" -p "$port" -y "$yaws_port" stop > /dev/null 2>&1
         exit 1
     fi
-    sleep 3s # let Scalaris settle
+
+    # Check if Scalaris node has been started.
+    sleep 2s # let Scalaris settle
+    max_tries=58
+    try=0
+    while [ $try -lt $max_tries ] ; do
+      scalaris_nodes_count_actual="$(scalariscall "Res = rpc:call('$NODE_NAME', admin, number_of_nodes, []), io:format(\"~p~n\", [Res]), halt(0)." | head -n1)"
+
+      if [ "$scalaris_nodes_count_actual" -ge "1" ] ; then
+        break
+      fi
+
+      try=$((10#$try + 1))
+      sleep 1s
+
+      if [ $try -eq $max_tries ] ; then
+        echo -e "  Starting Scalaris \x1b[1;31mFAILED\x1b[0m"
+        echo "  we were trying to run: $0 -f -s -m -d start"
+        # try to stop anyway (it could have been a false alarm):
+        $0 -c "$SCALARIS_COOKIE" -e "$erl_flags" -d -f -s -m -n "$NODE_NAME" -p "$port" -y "$yaws_port" stop > /dev/null 2>&1
+        exit 1
+      fi
+    done
+
     # bench parameters:
     BENCH_NR_OPS=10
     BENCH_TPN=1 # threads per node
