scalarisctl: -t decides start-type

diff --git a/trunk/bin/scalarisctl.in b/trunk/bin/scalarisctl.in
--- a/trunk/bin/scalarisctl.in
+++ b/trunk/bin/scalarisctl.in
@@ -55,7 +55,6 @@ NODE_NAME=node1
 ERLANG_HOSTNAME=${ERLANG_HOSTNAME-""}
 daemonize=0
 first=0
-first_quorum=0
 verbose=0
 port=""
 yaws_port=""
@@ -74,9 +73,6 @@ usage(){
     echo "    -d          - daemonize"
     echo "    --screen    - if daemonized, put an interactive session into screen"
     echo "    -e <params> - pass additional parameters to erl"
-    echo "    -f          - first node (to start a new Scalaris instead of joining one)"
-    echo "                  (not with -q)"
-    echo "    -q          - elect first node from known hosts (not with -f)"
     echo "    -n <name>   - Erlang process name (default 'node')"
     echo "    -c <cookie> - Erlang cookie to use (for distributed Erlang)"
     echo "                  (default '`get_cookie`')"
@@ -90,6 +86,7 @@ usage(){
     echo "                - (single) port distributed erlang listens on"
     echo "    --nodes-per-vm <number>"
     echo "                - number of Scalaris nodes to start inside the VM"
+    echo "    -t <stype>  - select start type: first|joining|quorum|recover|nostart"
     echo " services:"
     echo "    -m          - global Scalaris management server"
     echo "    -s          - Scalaris node (see also -f)"
@@ -417,13 +414,13 @@ checkinstallation() {
         export SCALARIS_ADDITIONAL_PARAMETERS="-scalaris mgmt_server {{127,0,0,1},$port,mgmt_server} -scalaris known_hosts [{{127,0,0,1},$port,service_per_vm}]"
     fi
     export SCALARIS_JAPI_NODE="$NODE_NAME"
-    $0 -c "$SCALARIS_COOKIE" -e "$erl_flags" -d -f -s -m -n "$NODE_NAME" -p "$port" -y "$yaws_port" start > /dev/null 2>&1
+    $0 -c "$SCALARIS_COOKIE" -e "$erl_flags" -d -t first -s -m -n "$NODE_NAME" -p "$port" -y "$yaws_port" start > /dev/null 2>&1
     FAILED=$?
     if [ $FAILED -ne 0 ]; then
         echo -e "  Starting Scalaris \x1b[1;31mFAILED\x1b[0m"
-        echo "  we were trying to run: $0 -f -s -m -d start"
+        echo "  we were trying to run: $0 -t nostart -s -m -d start"
         # try to stop anyway (it could have been a false alarm):
-        $0 -c "$SCALARIS_COOKIE" -e "$erl_flags" -d -f -s -m -n "$NODE_NAME" -p "$port" -y "$yaws_port" stop > /dev/null 2>&1
+        $0 -c "$SCALARIS_COOKIE" -e "$erl_flags" -d -t first -s -m -n "$NODE_NAME" -p "$port" -y "$yaws_port" stop > /dev/null 2>&1
         exit 1
     fi
 
@@ -446,9 +443,9 @@ checkinstallation() {
       if [ $try -eq $max_tries ] ; then
         echo -e "  Starting Scalaris \x1b[1;31mFAILED\x1b[0m"
         echo "  (result: ${scalaris_nodes_count_actual})."
-        echo "  we were trying to run: $0 -f -s -m -d start"
+        echo "  we were trying to run: $0 -t first -s -m -d start"
         # try to stop anyway (it could have been a false alarm):
-        $0 -c "$SCALARIS_COOKIE" -e "$erl_flags" -d -f -s -m -n "$NODE_NAME" -p "$port" -y "$yaws_port" stop > /dev/null 2>&1
+        $0 -c "$SCALARIS_COOKIE" -e "$erl_flags" -d -t first -s -m -n "$NODE_NAME" -p "$port" -y "$yaws_port" stop > /dev/null 2>&1
         exit 1
       fi
     done
@@ -636,13 +633,7 @@ checkinstallation() {
     exit 0
 }
 
-scalarisrecover(){
-    scalarisstart recover
-}
-
 scalarisstart(){
-    START_TYPE=${1-"start"}
-    shift
     $ERL -noinput -name $NODE_NAME -eval 'halt(0).' 2>/dev/null > /dev/null
     FAILED=$?
     if [ $FAILED -ne 0 ]; then
@@ -672,11 +663,11 @@ scalarisstart(){
     fi
     local tmp
     tmp=""
-    if [ $first -eq 1 ]; then
-        tmp="$tmp -scalaris first true"
-    fi
-    if [ $first_quorum -eq 1 ]; then
-        tmp="$tmp -scalaris first_quorum true"
+    if [ "$start_type" != "" ]; then
+        tmp="$tmp -scalaris start_type $start_type"
+    else
+      echo "the start-type is missing"
+      exit 1
     fi
     if [ "$port" != "" ]; then
         tmp="$tmp -scalaris port $port"
@@ -713,7 +704,6 @@ scalarisstart(){
  -pa $BEAMDIR $TOKEFLAGS $BACKGROUND\
  -sasl sasl_error_logger false\
  -yaws embedded true\
- -scalaris start_type \"$START_TYPE\"\
  -scalaris log_path \"\\\"$LOGDIR/$NODE_NAME\\\"\"\
  -scalaris docroot \"\\\"$DOCROOTDIR\\\"\"\
  -scalaris config \"\\\"$ETCDIR/scalaris.cfg\\\"\"\
@@ -827,7 +817,7 @@ until [ -z "$1" ]; do
       shift
       NODES_PER_VM=$1
       shift;;
-    checkinstallation | start | stop | gstop | restart | recover | list | debug | status)
+    checkinstallation | start | stop | gstop | restart | list | debug | status)
       cmd="$1"
       shift;;
     "dbg-check-ring")
@@ -838,13 +828,11 @@ until [ -z "$1" ]; do
       DBG_CHECK_RING_TIMEOUT=$1
       shift;;
     *)
-      if getopts "dhifqmsvn:p:y:k:e:c:l:" optionName; then
+      if getopts "dhifqmsvn:p:y:k:e:c:l:t:" optionName; then
         case "$optionName" in
             c) SCALARIS_COOKIE=$OPTARG;;
             e) erl_flags=$OPTARG;;
             d) daemonize=1;;
-            f) first=1;;
-            q) first_quorum=1;;
             h) usage 0;;
             i) echo "WARN: interactive is now default";;
             k) join_at=$OPTARG;;
@@ -854,6 +842,7 @@ until [ -z "$1" ]; do
             y) yaws_port=$OPTARG;;
             m) start_mgmt_server=1;;
             s) start_dht_node="dht_node";;
+            t) start_type=$OPTARG;;
             v) echo setting verbose from cli
                verbose=1;;
           [?]) echo "Wrong parameter $1."
@@ -883,8 +872,6 @@ case $cmd in
     restart)
         scalarisstop
         scalarisstart;;
-    recover)
-        scalarisrecover;;
     list)
         list_erlang_processes;;
     debug)
